### ISSUE TITLE
Zenoh in Docker does not load plugins from /root/.zenoh/lib

### ISSUE THREAD

**Issue by philrhc** [eclipse-zenoh/zenoh#1031]
### Describe the bug

Zenoh router does not load plugins from /root/.zenoh/lib

- Followed the steps here: https://zenoh.io/docs/getting-started/quick-test/#adding-plugins-and-backends-to-the-container
- Attached shell shows the .so files in `/root/.zenoh/lib`
- See the log line `2024-05-15T14:30:14.863318Z DEBUG main ThreadId(01) zenoh_util::std_only::lib_loader: Search for library libzenoh_plugin_rest.so to load in ["/", "/root/.zenoh/lib", "/usr/local/lib", "/usr/lib", "/"]`
- See the below response:
```
curl 'http://localhost:8000/@/router/local'
[
{ "key": "@/router/79887a32dad6ef34f82f4ed312390b69", "value": {"locators":["tcp/172.29.0.2:7447"],"metadata":null,"plugins":{"rest":{"path":"/libzenoh_plugin_rest.so"}},"sessions":[],"version":"v0.11.0-rc.3 built with rustc 1.72.0 (5680fa18f 2023-08-23)","zid":"79887a32dad6ef34f82f4ed312390b69"}, "encoding": "application/json", "time": "None" }
]
```

### To reproduce

Created a minimum repo w/ the docker compose but should be fairly easy to test w/ a docker compose file
https://github.com/philrhc/zenoh_docker_plugins

### System info

OS: Ubuntu 22.04.4 LTS
Arch: x86_64
CPU: 12th Gen Intel(R) Core(TM) i7-1265U
version:v0.11.0-rc.3 built with rustc 1.72.0 (5680fa18f 2023-08-23)
zid:79887a32dad6ef34f82f4ed312390b69

**Comment by philrhc** [comment]
ok, closing because i don't think this is a bug, i think it is a fault in the documentation. I'll continue investigating...

**Comment by philrhc** [comment]
if anyone else has the same problem, this should be helpful:
https://github.com/xvanov/advrob-project/blob/zenoh-router/desktop/compose.yaml

**Comment by alex-quilt** [comment]
This seems to still be an issue with the documentation, which I believe they're referring to in https://github.com/eclipse-zenoh/zenoh/pull/1593. For example, the compose.yaml in https://zenoh.io/docs/getting-started/quick-test/ should be:
```
services:
  zenoh:
    image: eclipse/zenoh
    restart: unless-stopped
    ports:
      - 7447:7447
      - 8000:8000
    volumes:
      - ./zenoh_docker:/root/.zenoh
    environment:
      - RUST_LOG=debug
    command: ['--rest-http-port=8000']
```
